# Site settings
title: My Jekyll Site
description: >-
  A simple site powered by Jekyll and GitHub Pages.
  (This text can span multiple lines.)
baseurl: "" # Leave empty for a personal site; add "/repo-name" for a project site
url: "https://neu-coop-2024.github.io/Syntax-Highlighting-Tutorial/" # Replace <username> with your GitHub username

# Author settings
author:
  name: Kevin Yang
  email: kevingyang72@gmail.com

# Theme (default themes supported by GitHub Pages)
theme: minima # Replace with another theme name if you're using a custom one

# Markdown settings
markdown: kramdown
highlighter: rouge # Code syntax highlighting

# Build settings
plugins:
  - jekyll-feed # Optional: Generates an RSS feed for your blog
  - jekyll-sitemap # Optional: Generates a sitemap.xml
exclude:
  - node_modules
  - vendor
